/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package SpeakerEvent.model.impl;

import SpeakerEvent.model.Speaker_Event;

import SpeakerEvent.service.Speaker_EventLocalServiceUtil;

import aQute.bnd.annotation.ProviderType;

/**
 * The extended model base implementation for the Speaker_Event service. Represents a row in the &quot;FOO_Speaker_Event&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Speaker_EventImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Speaker_EventImpl
 * @see Speaker_Event
 * @generated
 */
@ProviderType
public abstract class Speaker_EventBaseImpl extends Speaker_EventModelImpl
	implements Speaker_Event {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a speaker_ event model instance should use the {@link Speaker_Event} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			Speaker_EventLocalServiceUtil.addSpeaker_Event(this);
		}
		else {
			Speaker_EventLocalServiceUtil.updateSpeaker_Event(this);
		}
	}
}