/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package SpeakerEvent.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Speaker_Event service. Represents a row in the &quot;FOO_Speaker_Event&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link SpeakerEvent.model.impl.Speaker_EventModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SpeakerEvent.model.impl.Speaker_EventImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Speaker_Event
 * @see SpeakerEvent.model.impl.Speaker_EventImpl
 * @see SpeakerEvent.model.impl.Speaker_EventModelImpl
 * @generated
 */
@ProviderType
public interface Speaker_EventModel extends BaseModel<Speaker_Event> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a speaker_ event model instance should use the {@link Speaker_Event} interface instead.
	 */

	/**
	 * Returns the primary key of this speaker_ event.
	 *
	 * @return the primary key of this speaker_ event
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this speaker_ event.
	 *
	 * @param primaryKey the primary key of this speaker_ event
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this speaker_ event.
	 *
	 * @return the ID of this speaker_ event
	 */
	public long getId();

	/**
	 * Sets the ID of this speaker_ event.
	 *
	 * @param id the ID of this speaker_ event
	 */
	public void setId(long id);

	/**
	 * Returns the speaker ID of this speaker_ event.
	 *
	 * @return the speaker ID of this speaker_ event
	 */
	public long getSpeakerId();

	/**
	 * Sets the speaker ID of this speaker_ event.
	 *
	 * @param speakerId the speaker ID of this speaker_ event
	 */
	public void setSpeakerId(long speakerId);

	/**
	 * Returns the event ID of this speaker_ event.
	 *
	 * @return the event ID of this speaker_ event
	 */
	public long getEventId();

	/**
	 * Sets the event ID of this speaker_ event.
	 *
	 * @param eventId the event ID of this speaker_ event
	 */
	public void setEventId(long eventId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SpeakerEvent.model.Speaker_Event speaker_Event);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SpeakerEvent.model.Speaker_Event> toCacheModel();

	@Override
	public SpeakerEvent.model.Speaker_Event toEscapedModel();

	@Override
	public SpeakerEvent.model.Speaker_Event toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}